// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBenchmark() {
  return window['go']['main']['App']['CancelBenchmark']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ComputeTestSize(arg1, arg2) {
  return window['go']['main']['App']['ComputeTestSize'](arg1, arg2);
}

export function CopyToClipboard() {
  return window['go']['main']['App']['CopyToClipboard']();
}

export function FormatBytes(arg1) {
  return window['go']['main']['App']['FormatBytes'](arg1);
}

export function FormatSpeed(arg1) {
  return window['go']['main']['App']['FormatSpeed'](arg1);
}

export function GetAbsPath(arg1) {
  return window['go']['main']['App']['GetAbsPath'](arg1);
}

export function GetDefaultPath() {
  return window['go']['main']['App']['GetDefaultPath']();
}

export function GetOSInfo() {
  return window['go']['main']['App']['GetOSInfo']();
}

export function GetSystemInfo(arg1) {
  return window['go']['main']['App']['GetSystemInfo'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveHTMLReport() {
  return window['go']['main']['App']['SaveHTMLReport']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartBenchmark(arg1, arg2) {
  return window['go']['main']['App']['StartBenchmark'](arg1, arg2);
}
