// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelBenchmark():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ComputeTestSize(arg1:string,arg2:string):Promise<number>;

export function CopyToClipboard():Promise<void>;

export function FormatBytes(arg1:number):Promise<string>;

export function FormatSpeed(arg1:number):Promise<string>;

export function GetAbsPath(arg1:string):Promise<string>;

export function GetDefaultPath():Promise<string>;

export function GetOSInfo():Promise<Record<string, string>>;

export function GetSystemInfo(arg1:string):Promise<main.SystemInfoJSON>;

export function GetVersion():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveHTMLReport():Promise<string>;

export function SelectDirectory():Promise<string>;

export function StartBenchmark(arg1:string,arg2:string):Promise<void>;
